import Head from 'next/head';
// import Image from "next/image";
import { Inter } from 'next/font/google';
import { InputQuery } from '../components/InputQuery';
import { MapComponent } from '../components/Map/Map';
import { ListSuggestions } from '../components/ListSuggestions';

import { useState, useRef, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const [textInput, setTextInput] = useState('');
	const [geoData, setGeoData] = useState([]);
	const [queryBounds, setQueryBounds] = useState([]);
	const [resultGPT, setResultGPT] = useState(null);
	const [errorText, setErrorText] = useState(null);
	const [bestPlace, setBestPlace] = useState([]);

	return (
		<>
			<Head>
				<title>K.I.ez Guide</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col items-center">
				<h3 className="text-slate-900 text-xl my-6">K.I.ez Guide 🧭</h3>
				<InputQuery
					setGeoData={setGeoData}
					queryBounds={queryBounds}
					setResultGPT={setResultGPT}
					textInput={textInput}
					setTextInput={setTextInput}
					setErrorText={setErrorText}
				/>
				<p className="italic text-lg">"{textInput}"</p>
				<ListSuggestions
					resultGPT={resultGPT}
					geoData={geoData}
					textInput={textInput}
					setBestPlace={setBestPlace}
					setResultGPT={setResultGPT}
				/>
				<div className="w-3/4 h-[400px] pb-8">
					<MapComponent
						markerData={geoData}
						setQueryBounds={setQueryBounds}
						bestPlace={bestPlace}
					/>
				</div>
				{errorText ? <p>errorText: {errorText}</p> : null}
			</main>
		</>
	);
}
