import Head from 'next/head';
// import Image from "next/image";
import { Inter } from 'next/font/google';
import { QueryInput } from '../components/QueryInput';
import { MapComponent } from '../components/Map/Map';
import { GptResults } from '../components/GptResults';

import { useState, useRef, useEffect } from 'react';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	const [textInput, setTextInput] = useState('');
	const [geoData, setGeoData] = useState([]);
	const [queryBounds, setQueryBounds] = useState([]);
	const [resultGPT, setResultGPT] = useState(null);
	const [errorText, setErrorText] = useState(null);

	const [resultSzenarioCoordinates, setResultSzenarioCoordinates] = useState(
		[]
	);

	return (
		<>
			<Head>
				<title>K.I.ez Guide</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex flex-col items-center">
				<h3 className="text-slate-900 text-xl mb-3">K.I.ez Guide 🧭</h3>
				<QueryInput
					setGeoData={setGeoData}
					queryBounds={queryBounds}
					resultGPT={resultGPT}
					setResultGPT={setResultGPT}
					textInput={textInput}
					setTextInput={setTextInput}
					setErrorText={setErrorText}
				/>
				<p className="italic text-lg">"{textInput}"</p>
				<GptResults
					resultGPT={resultGPT}
					geoData={geoData}
					textInput={textInput}
					setResultSzenarioCoordinates={setResultSzenarioCoordinates}
				/>
				<div className="w-3/4 h-[400px] pb-8">
					<MapComponent
						markerData={geoData}
						setQueryBounds={setQueryBounds}
						resultSzenarioCoordinates={resultSzenarioCoordinates}
					/>
				</div>
			</main>
		</>
	);
}
