CREATE EXTENSION IF NOT EXISTS "vector" WITH SCHEMA "extensions";

CREATE TABLE "public"."requests" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"tag" text[],
	"description" text,
	"emoji" text,
	"help" text,
	"session_id" text
);

CREATE UNIQUE INDEX requests_pkey ON public.requests USING btree (id);

ALTER TABLE "public"."requests"
	ADD CONSTRAINT "requests_pkey" PRIMARY KEY USING INDEX "requests_pkey";

